### Working With Matrix in Python  

In [1]:
import numpy as np

creating a matrix using Numpy

In [2]:
matrix_1 = np.array([[2, 3], [6, 7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[1, 2, 44], [3, 4, 55], [5, 6, 77]])
print(matrix_2)
matrix_2.shape

[[ 1  2 44]
 [ 3  4 55]
 [ 5  6 77]]


(3, 3)

Creating a Matrix with Random Values 

In [5]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.22906033 0.95010839 0.26105302 0.29298024]
 [0.02419336 0.86114207 0.77929105 0.68636764]
 [0.5434525  0.37767543 0.15148064 0.55157805]]


creating Matrix with Random Integers 

In [6]:
ramdom_integerMatrix = np.random.randint(100, size=(4,5))
print(ramdom_integerMatrix)

[[95 88 98 13 69]
 [69 53 27 58  9]
 [68 64 17 75  0]
 [53 39 49 16 29]]


Matrix with all the value as 1  

In [7]:
matrix_3 = np.ones((2, 3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
matrix_3 = np.ones((10, 10))
print(matrix_3)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Null Matrix or Zero Matrix 

In [9]:
null_matrix = np.zeros((3, 4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity Matrix 

In [10]:
indentity_matrix = np.eye(3,3)
print(indentity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of Matrix 

In [11]:
# Matrix with Random integer values.

In [12]:
a = np.random.randint(100, size=(4,5))
print(a)

[[78 53  5 30 10]
 [43 85 40 69 15]
 [71 27 80 92 38]
 [42  4 61 85 29]]


In [13]:
transPose_a = np.transpose(a)
print(transPose_a)

[[78 43 71 42]
 [53 85 27  4]
 [ 5 40 80 61]
 [30 69 92 85]
 [10 15 38 29]]


### important operations on Matrix 

Matrix Additions and Subtraction can be added only if the have the same shape, that is both matrix should have the same no. of row and coloumn

Multiplication -- the no of coloumn in the first matrix should be equals to number of row in the second matrix 

importing Numpy Library

In [ ]:
import numpy as np

# Matrix Addition 

two Matrices can be added only if they have the row and coloumn (same shape)

In [15]:
# creating the two Matrix

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:", A)
print("Matrix B:", B)

Matrix A: [[1 2]
 [3 4]]
Matrix B: [[5 6]
 [7 8]]


In [16]:
A.shape

(2, 2)

In [17]:
B.shape

(2, 2)

# Adding two Matrices 

In [18]:
sum = A + B
print("Sum of A and B:", sum)

Sum of A and B: [[ 6  8]
 [10 12]]


In [24]:
# another way to add two matrix

matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(30, size=(3, 3))
print("Matrix 1:\n", matrix_1)
print("Matrix 2:\n", matrix_2)

matrix_sum = np.add(matrix_1, matrix_2)
print("Sum of Matrix 1 and Matrix 2:\n", matrix_sum)

Matrix 1:
 [[7 8 4]
 [1 7 4]
 [3 2 5]]
Matrix 2:
 [[ 8  6 18]
 [27 27  0]
 [14  3  0]]
Sum of Matrix 1 and Matrix 2:
 [[15 14 22]
 [28 34  4]
 [17  5  5]]


# Subtraction of two Matrices 

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:", A)
print("Matrix B:", B)

Matrix A: [[1 2]
 [3 4]]
Matrix B: [[5 6]
 [7 8]]


In [26]:
difference = A - B
print("Difference of A and B:", difference)

Difference of A and B: [[-4 -4]
 [-4 -4]]


In [27]:
matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(30, size=(3, 3))
print("Matrix 1:\n", matrix_1)
print("Matrix 2:\n", matrix_2)

Matrix 1:
 [[7 9 4]
 [7 8 2]
 [5 2 6]]
Matrix 2:
 [[21 17 23]
 [27 29  9]
 [27 17 15]]


In [28]:
subtarction = np.subtract(matrix_1, matrix_2)
print("Subtraction of Matrix 1 and Matrix 2:\n", subtarction)

Subtraction of Matrix 1 and Matrix 2:
 [[-14  -8 -19]
 [-20 -21  -7]
 [-22 -15  -9]]


# mutlipliying a matrix by scalr

In [31]:
x = 5 
y = np.array([[1, 2, 3], [9, 4, 3]])
result = x * y
print("Result of multiplying scalar x with matrix y:\n", result)

Result of multiplying scalar x with matrix y:
 [[ 5 10 15]
 [45 20 15]]


### Miltpliying 2 matrix 

In [32]:
matrix3 = np.random.randint(10, size=(3, 3))
matrix4 = np.random.randint(30, size=(3, 5))
try:
    product = np.dot(matrix3, matrix4)
    print("Product of Matrix 3 and Matrix 4:\n", product)
except ValueError as e:
    print("Error:", e)

Product of Matrix 3 and Matrix 4:
 [[196 287 350 378 210]
 [178 174 301 274 308]
 [167 176 253 295 291]]


In [35]:
matrix3 = np.random.randint(10, size=(3, 3))
matrix4 = np.random.randint(30, size=(4, 5))
try:
    product = np.dot(matrix3, matrix4)
    print("Product of Matrix 3 and Matrix 4:\n", product)
except ValueError as e:
    print("Error:", e)

Error: shapes (3,3) and (4,5) not aligned: 3 (dim 1) != 4 (dim 0)


# Element wise  MAtrix Multiplication 

In [36]:
matrix3 = np.random.randint(10, size=(3, 3))
matrix4 = np.random.randint(30, size=(3, 3))

In [39]:
product = np.multiply(matrix3, matrix4)
print("Product of Matrix 3 and Matrix 4:\n", product)

Product of Matrix 3 and Matrix 4:
 [[ 45   9  56]
 [  9   0 189]
 [ 15  27 150]]
